### ISSUE TITLE
Skipping YYY (https://xxxxx@xxx:*****@github.com/XXX/YYY.git) since it's not initalized

### ISSUE THREAD

**Issue by michael-dev2rights** [josegonzalez/python-github-backup#40] opened 2016-07-22 10:19 UTC
If I run

```
~/.local/bin/github-backup -u xxxxxx@xxx XXX -o repos  --all --private
```

From my account on an organisation where I have access to a set of private repos but have never forked or cloned anything I get a message like 

   Skipping YYY (https://xxxxx@xxx:*****@github.com/XXX/YYY.git) since it's not initalized

And the repos output with this message are not backed up however even so the script gives a success (0) return code.  

Looking at the repos that I am backuing up they all have content and are initialised so I don't understand this message.  I assume that it's not telling me that the target repository is not initialised since I'd assume it's meant to create that its self.

**Comment by josegonzalez** [comment] 2016-08-21 00:51
What was YYY? Can you show me how to reproduce this with a new account?

**Comment by jon-f** [comment] 2016-11-16 17:45
YYY would have been the name of repository which the script skips.  Setting -P -F to pull forks of private repos returns the same error, and unfortunately makes this script not very useful with these features being non-functional.

**Comment by josegonzalez** [comment] 2016-11-16 18:09
@jon-f not useful for your specific use case, but still useful for others.

Do you want to make a pull request for that functionality?

**Comment by jon-f** [comment] 2016-11-18 16:51
Sure, but aren't the -P and -F parameters existent as the script is supposed to give them function? Is anyone able to confirm whether they work at all?

**Comment by josegonzalez** [comment] 2016-11-18 17:16
Probably, but I don't use that functionality and the functionality I do use works just fine. If you want this to get fixed, you're going to have to do the work, because I'm certainly not going to.

**Comment by jon-f** [comment] 2016-11-18 19:19
lol.. Yeah I forked and will see if I can get it to work. Curious why you put the arguments in if the functionality didn't exist. When you first wrote the script did these arguments work?

**Comment by josegonzalez** [comment] 2016-11-18 19:51
I didn't add the `--fork` option. Maybe the dev who contributed that didn't test private forks?

**Comment by thebiggestfan** [comment] 2016-11-18 19:52
Yeah...I think we're on to something. Thanks.

**Comment by jon-f** [comment] 2016-11-18 19:53
Yeah...I think we're on to something. Thanks.

**Comment by josegonzalez** [comment] 2016-11-18 20:06
I really hope that's not condescension on your part, as - given no one has been paid to work on this software - it's pretty unappreciated.

I look forward to your pull request. Will like this issue open until the issue has been fixed in master.

**Closed** 2017-04-05 18:23 UTC
Labels: question
